apiVersion: container.gcp.upbound.io/v1beta1
kind: Cluster
metadata:
  name: newclusterwhodis
  labels: 
   cluster-name: newclusterwhodis
spec:
  forProvider:
    deletionProtection: false
    removeDefaultNodePool: true
    initialNodeCount: 1
    location: us-central1-b


---

apiVersion: container.gcp.upbound.io/v1beta1
kind: NodePool
metadata:
  name: newnodepoolwhodis
  labels:
    cluster-name: newclusterwhodis
spec:
  forProvider:
    clusterSelector:
      matchLabels:
        cluster-name: newclusterwhodis
    nodeCount: 1
    nodeConfig:
      - preemptible: true
        machineType: e2-medium
        oauthScopes:
          - https://www.googleapis.com/auth/cloud-platform
        labels:
          heckyesyoudidit: yourefrigginawesome
